const DEFAULT_POLLING_TIME = 15 // in minutes
const DEFAULT_HOUR_LIMIT = 48 // in hours
const DEFAULT_OFFSET = 0
const DEFAULT_LIMIT = 10

export {
  DEFAULT_POLLING_TIME,
  DEFAULT_HOUR_LIMIT,
  DEFAULT_OFFSET,
  DEFAULT_LIMIT
}
